#!/bin/sh
# this is a prerm script for aquachain debian package
set -e
if ! which systemctl >/dev/null; then
    echo "warn: systemd not found, skipping aquachain.service uninstallation"
    exit 0
fi
echo "stopping aquachain service: $@"
systemctl disable --now aquachain || pkill -u aqua -f aquachain || echo "warn: failed to stop aquachain service"
sleep 1
# systemctl disable --now aquachain || service stop aquachain
# sleep 1

# todo: purge etc